title: GM-Companion
subtitle: a tool for rpg gamemasters
description: >- # this means to ignore newlines until "baseurl:"
  This is the official GM-Companion website
author: Phil Hoffmann
email: phil.hoffmann@zoho.eu
avatar: assets/images/icon_square_256.png

# You'll want to customize url and baseurl for your own site:
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social settings
facebook_url:
github_url: https://github.com/PhilInTheGaps/GM-Companion
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Google Analytics Tracking ID goes here:
google_analytics:

# The following settings are NECESSARY for the Prologue theme to run:
theme: jekyll-theme-prologue
collections: [sections]

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
