baseURL = "https://gm-companion.github.io/"
title = "GM-Companion"

enableGitInfo = true
enableRobotsTXT = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]
[languages.en]
contentDir = "content/en"
languageName = "English"
weight = 1
[languages.en.params]
description = "User Documentation"

# [languages.de]
# description = "Dokumentation"
# languageName ="Deutsch"
# contentDir = "content/de"

[params]
privacy_policy = ""

github_branch = "master"
github_project_repo = "https://github.com/philinthegaps/gm-companion"
github_repo = "https://github.com/gm-companion/gm-companion.github.io"

[params.copyright]
from_year = 2017

[params.ui]
breadcrumb_disable = false # Set to true to disable breadcrumb navigation.
footer_about_enable = true # Set to false to disable the About link in the site footer
navbar_logo = false 
navbar_translucent_over_cover_disable = true # Set to true if you don't want the top navbar to be translucent when over a `block/cover`, like on the homepage.
sidebar_menu_compact = false # Enable to show the side bar menu in its compact state.
sidebar_menu_foldable = true
sidebar_search_disable = true # Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)

[params.ui.feedback]
enable = false

[params.links]
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
desc = "Development takes place here!"
icon = "fab fa-github"
name = "GitHub"
url = "https://github.com/philinthegaps/gm-companion"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
guessSyntax = true

[imaging]
anchor = "smart"
quality = 75
resampleFilter = "CatmullRom"

[[menu.main]]
name = "Download"
url = "/docs/install"
weight = 1

[[menu.main]]
name = "Getting Started"
url = "/docs/getting-started"
weight = 2

[module]
[module.hugoVersion]
extended = true
min = "0.110.0"
[[module.imports]]
disable = false
path = "github.com/google/docsy"
